#!/bin/bash

# General
alias x="exit"

# Git
alias g="git"
alias gco="git checkout"
alias gpo="git pull origin"
alias gpu="git push origin"
alias gst="git status"
alias glog="git log"

# Shortcut to push to Dokku
alias gpd="git push dokku"

# Quick access to GitHub Desktop app
alias gh="github"

alias ytd="youtube-dl"
