#!/bin/bash

# General
alias x="exit"

# Git
alias g="git"
alias gco="git checkout"
alias gpo="git pull origin"
alias gpu="git push origin"
alias gst="git status"
alias glog="git log"

# Shortcut to push to Dokku
alias gpd="git push dokku"

alias ytd="youtube-dl"

alias ia="open -a \"iA Writer\""

# Use The Silver Searcher to search only Ruby files
alias rbag="ag -G '.*\.rb\$'"

# Use The Silver Searcher to search only Ruby files, with 3 lines of context and ignoring test files.
alias rbusages='ag -C 3 -G ".*\.rb" --ignore "*test.rb"'

# Ruby / Rails
alias be="bundle exec"
